function designedFilter = FIR

% Generated by MATLAB(R) 26.1 and Signal Processing Toolbox 26.1.
% Generated on: 26-Apr-2026 23:46:13

designedFilter = designfilt('lowpassfir', ...
    'FilterOrder',5,'CutoffFrequency',40, ...
    'SampleRate',360);

end