function designedFilter = IIR

% Generated by MATLAB(R) 26.1 and Signal Processing Toolbox 26.1.
% Generated on: 26-Apr-2026 23:46:14

designedFilter = designfilt('lowpassiir', ...
    'FilterOrder',5,'HalfPowerFrequency',40, ...
    'SampleRate',360,'ScaleSOS',true);

end